In [1]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
dataset=pd.read_csv("Admission_Predict.csv")
dataset

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
395         1              0.82  
396         1              0.84  
397         1              0.91  
398         0              0.67  
399         1              0.95  

[400 rows x 9 columns]

In [3]:
dataset.drop(["Serial No."],axis=1,inplace=True)
dataset.head()

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   
1        324          107                  4  4.0   4.5  8.87         1   
2        316          104                  3  3.0   3.5  8.00         1   
3        322          110                  3  3.5   2.5  8.67         1   
4        314          103                  2  2.0   3.0  8.21         0   

   Chance of Admit   
0              0.92  
1              0.76  
2              0.72  
3              0.80  
4              0.65

In [4]:
x=dataset.iloc[:,:7].values
print(x)
y=dataset.iloc[:,7:].values
print(y)

[[337.   118.     4.   ...   4.5    9.65   1.  ]
 [324.   107.     4.   ...   4.5    8.87   1.  ]
 [316.   104.     3.   ...   3.5    8.     1.  ]
 ...
 [330.   116.     4.   ...   4.5    9.45   1.  ]
 [312.   103.     3.   ...   4.     8.78   0.  ]
 [333.   117.     4.   ...   4.     9.66   1.  ]]
[[0.92]
 [0.76]
 [0.72]
 [0.8 ]
 [0.65]
 [0.9 ]
 [0.75]
 [0.68]
 [0.5 ]
 [0.45]
 [0.52]
 [0.84]
 [0.78]
 [0.62]
 [0.61]
 [0.54]
 [0.66]
 [0.65]
 [0.63]
 [0.62]
 [0.64]
 [0.7 ]
 [0.94]
 [0.95]
 [0.97]
 [0.94]
 [0.76]
 [0.44]
 [0.46]
 [0.54]
 [0.65]
 [0.74]
 [0.91]
 [0.9 ]
 [0.94]
 [0.88]
 [0.64]
 [0.58]
 [0.52]
 [0.48]
 [0.46]
 [0.49]
 [0.53]
 [0.87]
 [0.91]
 [0.88]
 [0.86]
 [0.89]
 [0.82]
 [0.78]
 [0.76]
 [0.56]
 [0.78]
 [0.72]
 [0.7 ]
 [0.64]
 [0.64]
 [0.46]
 [0.36]
 [0.42]
 [0.48]
 [0.47]
 [0.54]
 [0.56]
 [0.52]
 [0.55]
 [0.61]
 [0.57]
 [0.68]
 [0.78]
 [0.94]
 [0.96]
 [0.93]
 [0.84]
 [0.74]
 [0.72]
 [0.74]
 [0.64]
 [0.44]
 [0.46]
 [0.5 ]
 [0.96]
 [0.92]
 [0.92]
 [0.94]
 [0.76]
 [0.72]
 [0.

In [5]:
print(x.shape)
print(y.shape)

(400, 7)
(400, 1)


In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 10)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[323.   107.     3.   ...   3.5    8.55   1.  ]
 [313.   101.     3.   ...   3.     8.04   0.  ]
 [311.   106.     2.   ...   3.     8.26   1.  ]
 ...
 [314.   105.     3.   ...   2.5    8.3    0.  ]
 [300.   100.     3.   ...   3.     8.66   1.  ]
 [313.   102.     3.   ...   2.5    8.68   0.  ]]
[[308.   106.     3.     3.5    2.5    8.21   1.  ]
 [321.   109.     4.     4.     4.     8.68   1.  ]
 [303.   100.     2.     3.     3.5    8.06   1.  ]
 [295.    99.     2.     2.5    3.     7.65   0.  ]
 [316.   102.     3.     2.     3.     7.4    0.  ]
 [311.    99.     1.     2.5    3.     8.43   1.  ]
 [340.   120.     4.     5.     5.     9.5    1.  ]
 [331.   117.     4.     4.5    5.     9.42   1.  ]
 [331.   115.     5.     4.     3.5    9.44   1.  ]
 [305.   108.     5.     3.     3.     8.48   0.  ]
 [327.   104.     5.     3.     3.5    8.84   1.  ]
 [322.   110.     4.     4.     5.     9.13   1.  ]
 [321.   109.     3.     3.     3.     8.54   1.  ]
 [315.   100.     1.    

In [7]:
y_train=(y_train>0.5)
y_train

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [

In [8]:
y_test=(y_test>0.5)
y_test

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [

In [10]:
from sklearn.linear_model import LogisticRegression
cls=LogisticRegression(random_state=0)
lr=cls.fit(x_train,y_train)
y_pred=lr.predict(x_test)
y_pred

C:\Users\KARUMANCHI\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\KARUMANCHI\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [11]:
from sklearn.metrics import accuracy_score,recall_score,roc_auc_score,confusion_matrix
print("\nAccuracy score: %f" %(accuracy_score(y_test,y_pred)*100))
print("\nRecall score: %f"%(recall_score(y_test,y_pred)*100))
print("\nROC score: %f"%(roc_auc_score(y_test,y_pred)*100))
print(confusion_matrix(y_test,y_pred))


Accuracy score: 91.250000

Recall score: 97.333333

ROC score: 48.666667
[[ 0  5]
 [ 2 73]]


In [13]:
import pickle
pickle.dump(lr,open('university.pkl','wb'))
model=pickle.load(open('university.pkl','rb'))